### ISSUE TITLE
CLJS-3138 is closed now, does that mean this workaround is no longer necessary?

### ISSUE THREAD

**Issue by fdhenard** [henryw374/tick-on-shadow-cljs-demo#1]
[The issue that is referenced in the readme](https://clojure.atlassian.net/browse/CLJS-3138) appears to be closed, does that mean that this workaround is no longer necessary?

https://clojure.atlassian.net/browse/CLJS-3138

**Comment by henryw374** [comment]
It will be unnecessary! I'm waiting on official cljs release then I'll remediate the libs and docs... Been prepping today ;-)

**Comment by fdhenard** [comment]
Thanks @henryw374! Any idea how long it takes for CLJS to release usually?  I'm trying to decide if I should do the workaround or wait.

**Comment by henryw374** [comment]
AFAIK it'll be released in the next week or two

**Comment by fdhenard** [comment]
Hi @henryw374, Sorry to bug you about this.  I upgraded to the new CLJS from this morning (1.10.739). I'm getting this when I run from my repl:

```
cljs.user> (require '[tick.alpha.api :as t])
------ REPL Error while processing ---------------------------------------------
(require '[tick.alpha.api :as t])
The required namespace "js-joda" is not available, it was required by "java/time.cljs".
The namespace was provided via :foreign-libs which is not supported.
Please refer to https://shadow-cljs.github.io/docs/UsersGuide.html#cljsjs for more information.
You may just need to run:
  npm install js-joda
```

Do I need to wait for a new tick release, or is something else wrong?

**Comment by henryw374** [comment]
Hi, yes a new release is needed. follow this ticket for progress: https://github.com/juxt/tick/issues/78

I'm waiting on some cljsjs PR's then it should be out pretty shortly after that.

**Comment by henryw374** [comment]
tick 0.4.24-alpha has been released
